# permissions for end users to view sli.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sli-viewer-role
rules:
- apiGroups:
  - sre.globo.com
  resources:
  - sli
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sre.globo.com
  resources:
  - sli/status
  verbs:
  - get
