# permissions for end users to view sloes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slo-viewer-role
rules:
- apiGroups:
  - sre.globo.com
  resources:
  - sloes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sre.globo.com
  resources:
  - sloes/status
  verbs:
  - get
